solved Sprint_04
Matthew-Develop/MovieQuiz pull request #1
Opened 2024-11-18 14:32 UTC by Matthew-Develop

2024-11-18 18:39 UTC, protos17 requested changes

2024-11-18 18:39 UTC, protos17 commented on MovieQuiz/Helpers/UIColor+Extensions.swift
> +    static var yGreen: UIColor { UIColor(named: "YP Green") ?? UIColor.green}
Здесь цвета написаны с большой буквы, а в `Assets` с маленькой буквы. Необходимо, чтобы они были написаны одинаково

2024-11-18 18:39 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
Лишние отступы рекомендую удалять, оставлять максимум 1

2024-11-18 18:39 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +import Foundation
При импорте UIKit можно не импортировать Foundation, потому что первый содержит в себе второй

2024-11-18 18:39 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            image: "The Godfather", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: true),
Если впорос везде повторяется, то рекомендую указать его как значение по умолчанию у поля `text` структуры `QuizQuestion`

2024-11-18 18:39 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        viewDidLoad()
Метод `viewDidLoad()` не стоит вызывать вручную

2024-11-18 18:39 UTC, protos17 commented on MovieQuiz/Resources/Assets.xcassets/Colors/YP red.colorset/Contents.json
Цвет написан с маленькой буквы, необходимо чтобы в extension Color и тут цвета должны быть написаны одинаково

2024-11-18 18:39 UTC, protos17 commented on MovieQuiz/Resources/Assets.xcassets/Colors/YP green.colorset/Contents.json
Название цвета не соответствует названию в extension

2024-11-19 05:30 UTC, Matthew-Develop commented
Добавил константу text вместо вопросов, убрал возможность нажатия кнопок до появления нового вопроса. по поводу цветов, у меня на компьютере в Xcode и в самих файлах в finder отображаются с большой буквы YP Green и YP Red и программа работает и отображает цвета (сейчас смотрю но в гитхабе все равно именно эти два с маленькой). Прикрепляю скрины из своих файлов, где видно что буквы большие
<img width="235" alt="Screenshot 2024-11-19 at 08 08 30" src="https://github.com/user-attachments/assets/09fedeab-d497-4d6d-adc6-ce735070e6e8">
<img width="735" alt="Screenshot 2024-11-19 at 08 09 01" src="https://github.com/user-attachments/assets/eeb33efe-1f1f-4002-9074-c44b033afc58">

2024-11-19 07:41 UTC, protos17 requested changes

2024-11-19 07:43 UTC, Matthew-Develop commented on MovieQuiz/Helpers/UIColor+Extensions.swift
> +    static var yGreen: UIColor { UIColor(named: "YP Green") ?? UIColor.green}
но у меня в файлах цвета видны как YP Red и YP Green

2024-11-19 08:39 UTC, Matthew-Develop commented
Сделал, только переименование не помогало, только добавление цветов заново

2024-11-20 07:02 UTC, protos17 approved these changes

2024-11-20 07:02 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            }
Не забывай следить за отступами, общепринятые отступы помогают читать код быстрее. В общем случае поможет выделить весь файл `cmd+A` и зажать `control+i`

2024-11-20 07:54 UTC, merged